-- Run this in the Supabase SQL Editor

-- 1. Drop existing table
drop table if exists ligar_devices;

-- 2. Create the table with ALL columns from CSV
-- CSV Headers: Id, Brand, Model, Date, Adapted, Created at, Updated at, Support ar core, Support camera two, 
-- Open gl es version, Device model name, Platform, Model numbers, Intr fx, Intr fy, Intr cx, Intr cy, 
-- Intr k1, Intr k2, Intr k3, Intr k4, Intr k5, Expo default, Focus default, Iso default, Img width, Img height

create table ligar_devices (
  -- We can keep our own ID or use the CSV ID. Let's use our own auto-inc ID for safety, 
  -- but store CSV ID in csv_id if needed. Or just ignore CSV Id and use serial.
  id bigint generated by default as identity primary key,
  
  csv_id text,                -- CSV: Id
  brand text,                 -- CSV: Brand
  model text,                 -- CSV: Model
  date_added text,            -- CSV: Date
  adapted boolean,            -- CSV: Adapted
  created_at_source text,     -- CSV: Created at (Text because format varies)
  updated_at_source text,     -- CSV: Updated at
  support_ar_core boolean,    -- CSV: Support ar core
  support_camera_two boolean, -- CSV: Support camera two
  open_gl_es_version text,    -- CSV: Open gl es version
  device_model_name text,     -- CSV: Device model name
  platform text,              -- CSV: Platform
  model_numbers text,         -- CSV: Model numbers (JSON-like string)
  
  -- Camera Intrinsics
  intr_fx numeric,
  intr_fy numeric,
  intr_cx numeric,
  intr_cy numeric,
  intr_k1 numeric,
  intr_k2 numeric,
  intr_k3 numeric,
  intr_k4 numeric,
  intr_k5 numeric,
  
  expo_default text,
  focus_default text,
  iso_default text,
  img_width numeric,
  img_height numeric,
  
  -- System fields
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Row Level Security (RLS)
alter table ligar_devices enable row level security;

-- 4. Create Policies
create policy "Allow public read access" 
on ligar_devices for select to anon using (true);

create policy "Allow authenticated insert" 
on ligar_devices for insert to authenticated with check (true);

create policy "Allow authenticated update" 
on ligar_devices for update to authenticated using (true);

create policy "Allow authenticated delete" 
on ligar_devices for delete to authenticated using (true);
